-- Up migration for quotes table
CREATE TABLE IF NOT EXISTS quotes (
	id SERIAL PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
	quote TEXT NOT NULL,
	author TEXT NOT NULL,
	version INT NOT NULL DEFAULT 1,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);